[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = admin
# Log settings
log_level = info
# Dev mode for easier debugging
# dev_mode = reload,qweb, Werkzeug,xml
