[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$AEDImdPam1NKScnZ./8/pw$ZaDnwEKnVKGBKLq9cfVUp6wnpIbAMYpzyt86pxa02TRsDNmGZcJoj5O1nCG6GIZ/XBvGKTcK5Hgwx9djTQJGDw
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
list_db = True
workers = 0
max_cron_threads = 0
data_dir = /var/lib/odoo
log_level = info

