from . import mer_delivery_discrepancy
from . import mer_delivery_discrepancy_wizard
from . import mer_discrepancy_report
from . import mer_purchase_request
from . import product_product
from . import product_template
from . import sale_order
from . import stock_picking
from . import stock_warehouse
from . import store_store
