{
    "name": "Store Management",
    "version": "19.0.1.0.0",
    "summary": "Quản lý danh mục cửa hàng, bổ sung hàng và vận hành tồn kho tại cửa hàng",
    "category": "Custom_Odoo",
    "author": "Tony",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "product",
        "stock",
        "sale_stock",
        "merchandise_management",
        "warehouse_management",
    ],
    "data": [
        "data/mer_excess_receipt_data.xml",
        "security/store_security.xml",
        "security/ir.model.access.csv",
        "views/store_menu_views.xml",
        "views/mer_delivery_discrepancy_views.xml",
        "views/mer_delivery_discrepancy_wizard_views.xml",
        "views/store_store_views.xml",
        "views/store_product_views.xml",
        "views/mer_purchase_request_views.xml",
        "views/sale_order_views.xml",
        "views/warehouse_management_integration_views.xml",
    ],
    "installable": True,
    "application": True,
}
